### ISSUE TITLE
Ensure that a deploy is not attempted immediately after configuration prompt

### ISSUE THREAD

**Issue by johndigital** [funkhaus/fh-deploy#9]
This was brought up in https://github.com/funkhaus/vuepress/issues/90

The first time fh-deploy is run and has no configuration, the user is prompted to add in their settings. When this happens the script should not attempt to run a deploy immediately after, because the user may not have set up their files array properly yet.

This may be the way it already works, but I believe I've seen this happen before so just wanted to make sure.

**Comment by SaFrMo** [comment]
This does need to be implemented, since it'll start to deploy immediately after setting up the config!

I can include a question at the end of the config setup that asks, "would you like to start deploying immediately? (y/N)" and defaults to no, since it is handy to be able to deploy right after creating the config sometimes.

**Comment by drewbaker** [comment]
I think the real problem is it doesn’t set the queue parameter up, and that doesn’t seem to be something you could define easily in a prompt. So in that case, I thought it would be easier to just mke the file for me and tell me to go edit that and then try it again.

**Comment by SaFrMo** [comment]
Added in 4dcd9aa
